# Generated by Django 4.0.5 on 2022-07-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alter_firm_name_alter_garbagerequest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagerequest',
            name='Address',
            field=models.ForeignKey(null=b'I00\n', on_delete=django.db.models.deletion.DO_NOTHING, to='new.firm'),
        ),
    ]
